
server.port=8000



#spring.datasource.url=jdbc:postgresql://localhost:5432/construction_expense_tracker
spring.datasource.url=jdbc:postgresql://dpg-d3nkuuhgv73c73cdta30-a.oregon-postgres.render.com:5432/construction_expense_tracker_ar39?sslmode=require
spring.datasource.username=construction_expense_tracker_ar39_user
spring.datasource.password=q4C9HgozymTCrKCqT0t11H0ADnrf2fGO

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================
# JPA Dialect
# =========================
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
